version = 1

test_patterns = ["Backend/Sanasoppa.API.Tests/**"]

exclude_patterns = ["**/Migrations/**"]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["angular"]

[[analyzers]]
name = "csharp"

[[transformers]]
name = "prettier"

[[transformers]]
name = "dotnet-format"