# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy frontend to azure staging

on:
  push:
    branches:
      - dev
    paths:
      - Frontend/Sanasoppa.UI/**
      - .github/workflows/build_and_deploy_frontend_staging.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build
        run: |
          cd Frontend/Sanasoppa.UI
          npm install
          npm run build --if-present
        env:
          AUTH0_DOMAIN: ${{ vars.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ vars.AUTH0_CLIENT_ID }}
          AUTH0_AUDIENCE: ${{ vars.AUTH0_AUDIENCE }}
          AUTH0_CALLBACK_URL: ${{ vars.AUTH0_CALLBACK_URL }}
          API_SERVER_URL: ${{ vars.API_SERVER_URL }}
          HUB_SERVER_URL: ${{ vars.HUB_SERVER_URL }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: Frontend/Sanasoppa.UI/dist/sanasoppa

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sanasoppa-stag'
          slot-name: 'Staging'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_511F411B5F04475291C409A34A8D27EA }}
          package: .
