name: Build and Test

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - Backend/**
      - .github/workflows/build-and-test.yml
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - Backend/**
      - .github/workflows/build-and-test.yml

env:
  SOLUTION_PATH: Backend/Sanasoppa.sln
  TEST_RESULTS_DIR: /tmp/test-results

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release
    - name: Test with coverage
      run: dotnet test ${{ env.SOLUTION_PATH }} --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger:"console;verbosity=detailed" --results-directory ${{ env.TEST_RESULTS_DIR }}

    - name: Report to DeepSource
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        curl https://deepsource.io/cli | sh
        echo "DEEPSOURCE_DSN=${{ secrets.DEEPSOURCE_DSN }}" >> $GITHUB_ENV
        COVERAGE_FILE=$(find ${{ env.TEST_RESULTS_DIR }} -name 'coverage.cobertura.xml')
        ./bin/deepsource report --analyzer test-coverage --key csharp --value-file $COVERAGE_FILE

    - name: Publish
      run: dotnet publish ${{ env.SOLUTION_PATH }} -c Release -o ${{env.DOTNET_ROOT}}/api
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: sanasoppa-api
        path: ${{env.DOTNET_ROOT}}/api
