# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore Backend/Sanasoppa.sln
    - name: Build
      run: dotnet build Backend/Sanasoppa.sln --no-restore
    - name: Test with coverage
      run: dotnet test Backend/Sanasoppa.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger:"console;verbosity=detailed" --results-directory /tmp/test-results/
    - name: Install DeepSource CLI
      run: curl https://deepsource.io/cli | sh
    - name: Set DEEPSOURCE_DSN env variable
      run: export DEEPSOURCE_DSN=${{ secrets.DEEPSOURCE_DSN }}
    - name: Report coverage to DeepSource
      run: |
        TRX_FILE=$(find /tmp/test-results -name '*.trx')
        TEST_GUID=$(grep -Po '<TestRun id="\K[^"]*' $TRX_FILE)
        ./bin/deepsource report --analyzer test-coverage --key csharp --value-file /tmp/test-results/$TEST_GUID/coverage.cobertura.xml
