# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - sanasoppa-api

on:
  push:
    branches:
      - main
    paths:
      - Backend/**
      - .github/workflows/main_sanasoppa-api.yml
  workflow_dispatch:

env:
  SOLUTION_PATH: Backend/Sanasoppa.sln
  TEST_RESULTS_DIR: /tmp/test-results
  CSPORJ_PATH: Backend/Sanasoppa.API/Sanasoppa.API.csproj

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}
        
      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release
        
      - name: Test with coverage
        run: dotnet test ${{ env.SOLUTION_PATH }} --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --logger:"console;verbosity=detailed" --results-directory ${{ env.TEST_RESULTS_DIR }}
        
      - name: dotnet publish
        run: dotnet publish ${{ env.CSPORJ_PATH }} -c Release -o ${{env.DOTNET_ROOT}}/prod-api

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: sanasoppa-api
          path: ${{env.DOTNET_ROOT}}/prod-api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: sanasoppa-api

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sanasoppa-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B3BAD5569FEE4E649983732329CC227D }}
          package: .
