name: Publish to DeepSource

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install DeepSource CLI
      run: curl https://deepsource.io/cli | sh
    - name: Set DEEPSOURCE_DSN env variable
      run: echo "DEEPSOURCE_DSN=${{ secrets.DEEPSOURCE_DSN }}" >> $GITHUB_ENV
    - name: Report coverage to DeepSource
      run: |
        COVERAGE_FILE=$(find /tmp/test-results -name 'coverage.cobertura.xml')
        ./bin/deepsource report --analyzer test-coverage --key csharp --value-file $COVERAGE_FILE
